
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

## Netatmo
netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret